Prevent extension search for .tmpl file popup
KreativJos/csharpextensions pull request #20
Opened 2020-11-27 20:01 UTC by PoLaKoSz

Steps to reproduce the issue:
1. Select `New C# Class` (or any option that uses the `openTemplateAndSaveNewFile` function)
1. This popup will appear:
![The Marketplace has extensions that can help with '.tmpl' files](https://user-images.githubusercontent.com/1327533/100481113-80bd2e00-30f3-11eb-8c2f-9cae61c132ab.png)

After the patch this won't happen.

2021-05-18 21:16 UTC, pm4rcin commented
@PoLaKoSz since the maintainer doesn't respond maybe move [here](https://github.com/Tdallau/csharpextensions)?

2021-05-20 22:18 UTC, KreativJos requested changes
Seems to be correct by reviewing alone. I cannot run any tests currently, probably because of the vscode engine version

2021-05-20 22:18 UTC, KreativJos commented on src/extension.ts
> +    fs.readFile(templateFilePath, 'utf8', (errTryingToCreate, fileContent) => {
errTryingToCreate - Error name is wrong here now, should be something like 'errorTryingToReadFile' or 'errorReading'

2021-05-23 11:26 UTC, PoLaKoSz commented
Thanks for the review. Rebased to master and before force push I checked out to master. My [`Ignore Recommendations`](https://stackoverflow.com/a/66958385/7306734) setting is not ticked, but I could not reproduce the popup so I'm gonna close this issue.

2021-05-26 14:15 UTC, KreativJos commented
Tested this on a fresh install of vscode insiders and the issue still exists. Your pull-request fixes the issue.

2021-05-26 14:19 UTC, merged

2021-05-26 17:29 UTC, PoLaKoSz commented
Wow, thank You! :)